name = "redisinsight"
version = "3.2.0"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/redis/RedisInsight/releases/download/3.2.0/Redis-Insight-linux-x86_64.AppImage"
sha256 = "6413db1e16d1cf0a291378a9ecc8495ddac06df39b8f30660d422d67eb8908fd"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/redis/RedisInsight/releases/download/3.2.0/Redis-Insight-mac-arm64.zip"
sha256 = "c91ba226e5f3e049f477750933e9324b4836d90326d8b731d3fea44307833806"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/redis/RedisInsight/releases/download/3.2.0/Redis-Insight-mac-x64.zip"
sha256 = "019ad91a367f5ddaa8b14d04c075e449d2b6de047ee37a7035de395e4c49da32"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/redis/RedisInsight/releases/download/3.2.0/Redis-Insight-win-installer.exe"
sha256 = "56c711522f1acb7d05576a9884786d931d067590f48ad80701d846fb60d2a94a"
