name = "ast-grep"
version = "0.42.1"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/ast-grep/ast-grep/releases/download/0.42.1/app-x86_64-unknown-linux-gnu.zip"
sha256 = "5de8b87cba67fc8dc3e239d54b6484802ad745a7ae3de76be4fe89661dc52657"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/ast-grep/ast-grep/releases/download/0.42.1/app-aarch64-unknown-linux-gnu.zip"
sha256 = "3ba383839044cf9817929435f5ce0027f91d06931e8efb32d942e58d73d92be5"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/ast-grep/ast-grep/releases/download/0.42.1/app-x86_64-apple-darwin.zip"
sha256 = "a038965bfd7fe44257c771cdf8918dc3467dd8ec0eef673b8b14f639b144cdbd"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/ast-grep/ast-grep/releases/download/0.42.1/app-aarch64-apple-darwin.zip"
sha256 = "c3961d8e8a4ee0ce2d0d98c7beeb168bb331cdc766b53630118a7b6c4fd39015"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/ast-grep/ast-grep/releases/download/0.42.1/app-x86_64-pc-windows-msvc.zip"
sha256 = "fe34f631bb24c08ad146f92ca2a92971a53d179461b509fd8d32dc863bff9f83"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
url = "https://github.com/ast-grep/ast-grep/releases/download/0.42.1/app-aarch64-pc-windows-msvc.zip"
sha256 = "c590f9b12c014fac5e751e08f91075732530a4495dfacf7cae93e8f867d27291"
