name = "delta"
license = "MIT"
homepage = "https://github.com/dandavison/delta"

[source]
provider = "github"
repo = "dandavison/delta"
include_prereleases = false

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
asset = "delta-{version}-x86_64-unknown-linux-gnu.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "delta"
path = "delta"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
asset = "delta-{version}-aarch64-unknown-linux-gnu.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "delta"
path = "delta"

[[artifacts]]
target = "x86_64-apple-darwin"
asset = "delta-{version}-x86_64-apple-darwin.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "delta"
path = "delta"

[[artifacts]]
target = "aarch64-apple-darwin"
asset = "delta-{version}-aarch64-apple-darwin.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "delta"
path = "delta"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
asset = "delta-{version}-x86_64-pc-windows-msvc.zip"
archive = "zip"
strip_components = 1

[[artifacts.binaries]]
name = "delta"
path = "delta.exe"
