name = "go"
license = "BSD-3-Clause"
homepage = "https://go.dev/"

[source.release]
kind = "go_dist_index"
include_prereleases = false

[source.checksum]
kind = "download_index"

[source.asset]
kind = "templated"
base_url = "https://go.dev/dl"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
asset = "go{version}.linux-amd64.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "go"
path = "bin/go"
[[artifacts.binaries]]
name = "gofmt"
path = "bin/gofmt"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
asset = "go{version}.linux-arm64.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "go"
path = "bin/go"
[[artifacts.binaries]]
name = "gofmt"
path = "bin/gofmt"

[[artifacts]]
target = "x86_64-apple-darwin"
asset = "go{version}.darwin-amd64.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "go"
path = "bin/go"
[[artifacts.binaries]]
name = "gofmt"
path = "bin/gofmt"

[[artifacts]]
target = "aarch64-apple-darwin"
asset = "go{version}.darwin-arm64.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "go"
path = "bin/go"
[[artifacts.binaries]]
name = "gofmt"
path = "bin/gofmt"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
asset = "go{version}.windows-amd64.zip"
archive = "zip"
strip_components = 1

[[artifacts.binaries]]
name = "go"
path = "bin/go.exe"
[[artifacts.binaries]]
name = "gofmt"
path = "bin/gofmt.exe"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
asset = "go{version}.windows-arm64.zip"
archive = "zip"
strip_components = 1

[[artifacts.binaries]]
name = "go"
path = "bin/go.exe"
[[artifacts.binaries]]
name = "gofmt"
path = "bin/gofmt.exe"
