name = "go"
license = "BSD-3-Clause"
homepage = "https://go.dev/"

[source.release]
kind = "json_index"
url = "https://go.dev/dl/?mode=json"
stable_field = "stable"

[source.version]
kind = "prefixed_semver_field"
field = "version"
prefix = "go"

[source.checksum]
kind = "download_index"

[source.asset]
kind = "json_index_asset"
asset_array_field = "files"
name_field = "filename"
checksum_field = "sha256"
url_template = "https://go.dev/dl/{asset}"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
asset = "go{version}.linux-amd64.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "go"
path = "bin/go"
[[artifacts.binaries]]
name = "gofmt"
path = "bin/gofmt"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
asset = "go{version}.linux-arm64.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "go"
path = "bin/go"
[[artifacts.binaries]]
name = "gofmt"
path = "bin/gofmt"

[[artifacts]]
target = "x86_64-apple-darwin"
asset = "go{version}.darwin-amd64.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "go"
path = "bin/go"
[[artifacts.binaries]]
name = "gofmt"
path = "bin/gofmt"

[[artifacts]]
target = "aarch64-apple-darwin"
asset = "go{version}.darwin-arm64.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "go"
path = "bin/go"
[[artifacts.binaries]]
name = "gofmt"
path = "bin/gofmt"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
asset = "go{version}.windows-amd64.zip"
archive = "zip"
strip_components = 1

[[artifacts.binaries]]
name = "go"
path = "bin/go.exe"
[[artifacts.binaries]]
name = "gofmt"
path = "bin/gofmt.exe"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
asset = "go{version}.windows-arm64.zip"
archive = "zip"
strip_components = 1

[[artifacts.binaries]]
name = "go"
path = "bin/go.exe"
[[artifacts.binaries]]
name = "gofmt"
path = "bin/gofmt.exe"
