name = "insomnia"
license = "Apache-2.0"
homepage = "https://github.com/Kong/insomnia"

[source]
provider = "github"
repo = "Kong/insomnia"
tag_prefix = "core@"
include_prereleases = false

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
asset = "Insomnia.Core-{version}.AppImage"
strip_components = 0

[[artifacts.binaries]]
name = "insomnia"
path = "insomnia"

[[artifacts.gui_apps]]
app_id = "com.insomnia.app"
display_name = "Insomnia"
exec = "insomnia"
categories = ["Development"]

[[artifacts]]
target = "x86_64-apple-darwin"
asset = "Insomnia.Core-{version}.dmg"
strip_components = 0

[[artifacts.binaries]]
name = "insomnia"
path = "Insomnia.app/Contents/MacOS/Insomnia"

[[artifacts.gui_apps]]
app_id = "com.insomnia.app"
display_name = "Insomnia"
exec = "Insomnia.app"
categories = ["Development"]

[[artifacts]]
target = "aarch64-apple-darwin"
asset = "Insomnia.Core-{version}.dmg"
strip_components = 0

[[artifacts.binaries]]
name = "insomnia"
path = "Insomnia.app/Contents/MacOS/Insomnia"

[[artifacts.gui_apps]]
app_id = "com.insomnia.app"
display_name = "Insomnia"
exec = "Insomnia.app"
categories = ["Development"]

[[artifacts]]
target = "x86_64-pc-windows-msvc"
asset = "Insomnia.Core-{version}.exe"
strip_components = 0

[[artifacts.binaries]]
name = "insomnia"
path = "insomnia.exe"

[[artifacts.gui_apps]]
app_id = "com.insomnia.app"
display_name = "Insomnia"
exec = "insomnia.exe"
categories = ["Development"]
