name = "jq"
license = "MIT"
homepage = "https://github.com/jqlang/jq"

[source]
provider = "github"
repo = "jqlang/jq"
include_prereleases = false

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
asset = "jq-linux-amd64"
archive = "bin"

[[artifacts.binaries]]
name = "jq"
path = "jq-linux-amd64"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
asset = "jq-linux-arm64"
archive = "bin"

[[artifacts.binaries]]
name = "jq"
path = "jq-linux-arm64"

[[artifacts]]
target = "x86_64-apple-darwin"
asset = "jq-macos-amd64"
archive = "bin"

[[artifacts.binaries]]
name = "jq"
path = "jq-macos-amd64"

[[artifacts]]
target = "aarch64-apple-darwin"
asset = "jq-macos-arm64"
archive = "bin"

[[artifacts.binaries]]
name = "jq"
path = "jq-macos-arm64"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
asset = "jq-windows-amd64.exe"

[[artifacts.binaries]]
name = "jq"
path = "jq-windows-amd64.exe"
