name = "zig"
license = "MIT"
homepage = "https://ziglang.org/"

[source.release]
kind = "zig_download_index"
include_prereleases = false

[source.checksum]
kind = "download_index"

[source.asset]
kind = "download_index"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
asset = "x86_64-linux"
archive = "tar.xz"
strip_components = 1

[[artifacts.binaries]]
name = "zig"
path = "zig"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
asset = "aarch64-linux"
archive = "tar.xz"
strip_components = 1

[[artifacts.binaries]]
name = "zig"
path = "zig"

[[artifacts]]
target = "x86_64-apple-darwin"
asset = "x86_64-macos"
archive = "tar.xz"
strip_components = 1

[[artifacts.binaries]]
name = "zig"
path = "zig"

[[artifacts]]
target = "aarch64-apple-darwin"
asset = "aarch64-macos"
archive = "tar.xz"
strip_components = 1

[[artifacts.binaries]]
name = "zig"
path = "zig"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
asset = "x86_64-windows"
archive = "zip"
strip_components = 1

[[artifacts.binaries]]
name = "zig"
path = "zig.exe"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
asset = "aarch64-windows"
archive = "zip"
strip_components = 1

[[artifacts.binaries]]
name = "zig"
path = "zig.exe"
