name = "lazydocker"
version = "0.25.2"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/jesseduffield/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_Linux_x86_64.tar.gz"
sha256 = "0d9dbfc26068b218e7ed84b104748cadc6e3cf733c0afd35465306fb39b9523c"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/jesseduffield/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_Linux_arm64.tar.gz"
sha256 = "005c38b685aaa557e7d646d83a3dadb5024340eeed8c6a2e1949eee6f530de23"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/jesseduffield/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_Darwin_x86_64.tar.gz"
sha256 = "af70b6e234089aa24924db25fc201d17f224e76d334e743e4595d30cf83a013b"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/jesseduffield/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_Darwin_arm64.tar.gz"
sha256 = "4a54d7b4abdf255b2bce9806641eac5568d5b7fbc820c1b5d3f9e34ea1367d60"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/jesseduffield/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_Windows_x86_64.zip"
sha256 = "facae8869c1bf144468191c563002162273a2c2761f052659170530cae3fa8a9"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
url = "https://github.com/jesseduffield/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_Windows_arm64.zip"
sha256 = "25a4f4708b7f73a0aeadde13c8d7a172baa5a1ebabccb062765c28ae93029903"
