name = "typos"
version = "1.45.1"

[[artifacts]]
target = "x86_64-unknown-linux-musl"
url = "https://github.com/crate-ci/typos/releases/download/v1.45.1/typos-v1.45.1-x86_64-unknown-linux-musl.tar.gz"
sha256 = "33447531a0eff29796d6fb9b555b4628723db72c6bad129e168d97ac86ceb0f1"

[[artifacts]]
target = "aarch64-unknown-linux-musl"
url = "https://github.com/crate-ci/typos/releases/download/v1.45.1/typos-v1.45.1-aarch64-unknown-linux-musl.tar.gz"
sha256 = "0d3688c607a49ffb6dedaca6de44e4217abeaa5b93228d673dc5caf76f60489f"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/crate-ci/typos/releases/download/v1.45.1/typos-v1.45.1-x86_64-apple-darwin.tar.gz"
sha256 = "70767b5d8d920cbb17b452a6b068e36e1b3fd649089bce883d3512eb85990326"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/crate-ci/typos/releases/download/v1.45.1/typos-v1.45.1-aarch64-apple-darwin.tar.gz"
sha256 = "2c31ed16286f26c08ae477faf001af8542ff23aeb6e7323be5f620710c192fb5"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/crate-ci/typos/releases/download/v1.45.1/typos-v1.45.1-x86_64-pc-windows-msvc.zip"
sha256 = "a4ae081cb7a403f2b75e8c066aa4a4484207547c4e9eb2b4df3f68ecdbc5dd3e"
