name = "zoxide"
version = "0.9.9"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.9/zoxide-0.9.9-x86_64-unknown-linux-musl.tar.gz"
sha256 = "4ff057d3c4d957946937274c2b8be7af2a9bbae7f90a1b5e9baaa7cb65a20caa"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.9/zoxide-0.9.9-aarch64-unknown-linux-musl.tar.gz"
sha256 = "96e6ea2e47a71db42cb7ad5a36e9209c8cb3708f8ae00f6945573d0d93315cb0"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.9/zoxide-0.9.9-x86_64-apple-darwin.tar.gz"
sha256 = "364249cff18354397c72ebb6b8f7358404c051c486e0f2f7a46e36c86c16f8c7"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.9/zoxide-0.9.9-aarch64-apple-darwin.tar.gz"
sha256 = "57e733d0436309dae2ed97e46bba43937209395298e1d88812d4e893900cb40a"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.9/zoxide-0.9.9-x86_64-pc-windows-msvc.zip"
sha256 = "5af00d0916f05631e3030537289eac56605e7c1733318c4d525c8e847f12496d"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
url = "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.9/zoxide-0.9.9-aarch64-pc-windows-msvc.zip"
sha256 = "58c55ef6f0ead099fbb31ed69566118d7c7c7a4e16c858bbdb4f7def40cd534b"
