name = "nushell"
version = "0.112.2"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/nushell/nushell/releases/download/0.112.2/nu-0.112.2-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "4038c171dd2618f2413a2aa615b8dab7e9d04852be8200f1755df3e422328395"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/nushell/nushell/releases/download/0.112.2/nu-0.112.2-aarch64-unknown-linux-gnu.tar.gz"
sha256 = "c25a713f4c10bd886162c62c278db6cf8a657754be53d33379af70fbadab07b8"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/nushell/nushell/releases/download/0.112.2/nu-0.112.2-x86_64-apple-darwin.tar.gz"
sha256 = "8de1dc4a918a1af29fce75d263a8f673f16d35c04ebaa5e3c3ac4ce1eb154f3f"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/nushell/nushell/releases/download/0.112.2/nu-0.112.2-aarch64-apple-darwin.tar.gz"
sha256 = "a61806761db7bc2eddfc313d5ec496c92776a37124bc64a3036374bd55e8c881"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/nushell/nushell/releases/download/0.112.2/nu-0.112.2-x86_64-pc-windows-msvc.zip"
sha256 = "db57750ec878365135e7baebee9f5ec74b84c80158ed0168f1ccbe15d6ec251d"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
url = "https://github.com/nushell/nushell/releases/download/0.112.2/nu-0.112.2-aarch64-pc-windows-msvc.zip"
sha256 = "badc7536bf502b3d46c5abf6dc84d394641f407617e6be99cc8346fe946c5550"
