name = "oras"
version = "1.3.2"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/oras-project/oras/releases/download/v1.3.2/oras_1.3.2_linux_amd64.tar.gz"
sha256 = "9229ccc6d17bb282039ad4a69abb16dcb887a5bce567c075d731d9b3c7ad8eaf"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/oras-project/oras/releases/download/v1.3.2/oras_1.3.2_linux_arm64.tar.gz"
sha256 = "8db4a223bd6034deff198e791ea7cb3af0840df25b7e9f370e2f1f3fd20d389b"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/oras-project/oras/releases/download/v1.3.2/oras_1.3.2_darwin_amd64.tar.gz"
sha256 = "2621f6b252b222f6fbf4e114d2fcaa0cec6b632624ffaf73143f66e4e0994f86"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/oras-project/oras/releases/download/v1.3.2/oras_1.3.2_darwin_arm64.tar.gz"
sha256 = "7929f792cf272268412375ecad6f0fb3c20f164368d5b57966e67ad6d36eca53"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/oras-project/oras/releases/download/v1.3.2/oras_1.3.2_windows_amd64.zip"
sha256 = "c896f26245f11e6385d52010bb0a65a4e500e1f3244680a6556ed05462fa1c0d"
