name = "karabiner-elements"
version = "16.0.0"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/pqrs-org/Karabiner-Elements/releases/download/v16.0.0/Karabiner-Elements-16.0.0.dmg"
sha256 = "b960f731890a74231c229e5453c4ee7109efb328c4fb63aed8974e347fd1f9c0"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/pqrs-org/Karabiner-Elements/releases/download/v16.0.0/Karabiner-Elements-16.0.0.dmg"
sha256 = "b960f731890a74231c229e5453c4ee7109efb328c4fb63aed8974e347fd1f9c0"
