name = "watchexec"
version = "2.5.1"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/watchexec/watchexec/releases/download/v2.5.1/watchexec-2.5.1-x86_64-unknown-linux-gnu.tar.xz"
sha256 = "cafc381f74e95f8e93e796ef590c7cbbf3409dda6d56cf3dee6109c10e5188ee"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/watchexec/watchexec/releases/download/v2.5.1/watchexec-2.5.1-aarch64-unknown-linux-gnu.tar.xz"
sha256 = "217e564946fec9911279c455e174e938d497480792a342c28712e50346cc0140"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/watchexec/watchexec/releases/download/v2.5.1/watchexec-2.5.1-x86_64-apple-darwin.tar.xz"
sha256 = "bb74bf33286ff7f31dd8e763e017fbc0418360d88baefd35bc57d662d28394e2"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/watchexec/watchexec/releases/download/v2.5.1/watchexec-2.5.1-aarch64-apple-darwin.tar.xz"
sha256 = "c5e405dd1109940b2510398d2182990c1be59063b94e11d7ace9c7b435cb1df1"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/watchexec/watchexec/releases/download/v2.5.1/watchexec-2.5.1-x86_64-pc-windows-msvc.zip"
sha256 = "aa448c2704ca1a37ce0f1fc75381d9a411946dd293cf6236293f549426a577f7"
