name = "lazygit"
version = "0.60.0"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/jesseduffield/lazygit/releases/download/v0.60.0/lazygit_0.60.0_linux_x86_64.tar.gz"
sha256 = "6252ca6cf98bc4fd3e0d927b54225910cfa57b065d0ad88263f14592f7f9ab15"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/jesseduffield/lazygit/releases/download/v0.60.0/lazygit_0.60.0_linux_arm64.tar.gz"
sha256 = "2c699579165416eede4d2cfaf7d76ccd8f3b20f20f2e8b4abff6b5a6350fcdd7"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/jesseduffield/lazygit/releases/download/v0.60.0/lazygit_0.60.0_darwin_x86_64.tar.gz"
sha256 = "9210a8bd8bf18537f9d7747361c8eba62518e10e4d5fbfe915cf110635eaab78"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/jesseduffield/lazygit/releases/download/v0.60.0/lazygit_0.60.0_darwin_arm64.tar.gz"
sha256 = "5045f0ff2117f12cb5232d65e01c054eb9ea6b8e2f0f0b80e99fbaa589b581b9"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/jesseduffield/lazygit/releases/download/v0.60.0/lazygit_0.60.0_windows_x86_64.zip"
sha256 = "435b53165ff4604e201549b9317eb0b8bb5b3f6728be612656988e90c821a9b9"
