name = "cmake"
version = "4.3.2"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/Kitware/CMake/releases/download/v4.3.2/cmake-4.3.2-linux-x86_64.tar.gz"
sha256 = "791ae3604841ca03cb3889a3ad89165346e4b180ae3448efd4b0caa9ef46d245"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/Kitware/CMake/releases/download/v4.3.2/cmake-4.3.2-linux-aarch64.tar.gz"
sha256 = "377079ab739f5765176f427609d9a2015b756ea20d5cba908d279c3731a2f481"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/Kitware/CMake/releases/download/v4.3.2/cmake-4.3.2-macos-universal.tar.gz"
sha256 = "808ab43a0db04c8eec9ed7db12b90d7be1c8e2e75f4a060724d604a2043ccaf7"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/Kitware/CMake/releases/download/v4.3.2/cmake-4.3.2-macos-universal.tar.gz"
sha256 = "808ab43a0db04c8eec9ed7db12b90d7be1c8e2e75f4a060724d604a2043ccaf7"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/Kitware/CMake/releases/download/v4.3.2/cmake-4.3.2-windows-x86_64.zip"
sha256 = "83d20c23f5c5f64b3b328785e35b23c532e33057a97ed6294acaca3781b78a01"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
url = "https://github.com/Kitware/CMake/releases/download/v4.3.2/cmake-4.3.2-windows-arm64.zip"
sha256 = "42a2a88fc57e70d04a92f6eaaac2094241995f53584bc2afdae7e6ef982b3781"
