name = "kustomize"
version = "5.8.1"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.8.1/kustomize_v5.8.1_linux_amd64.tar.gz"
sha256 = "029a7f0f4e1932c52a0476cf02a0fd855c0bb85694b82c338fc648dcb53a819d"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.8.1/kustomize_v5.8.1_linux_arm64.tar.gz"
sha256 = "0953ea3e476f66d6ddfcd911d750f5167b9365aa9491b2326398e289fef2c142"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.8.1/kustomize_v5.8.1_darwin_amd64.tar.gz"
sha256 = "ee7cf0c1e3592aa7bb66ba82b359933a95e7f2e0b36e5f53ed0a4535b017f2f8"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.8.1/kustomize_v5.8.1_darwin_arm64.tar.gz"
sha256 = "8886f8a78474e608cc81234f729fda188a9767da23e28925802f00ece2bab288"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.8.1/kustomize_v5.8.1_windows_amd64.zip"
sha256 = "8ec7f5e815e526d4622c06df0a7793d8cfb6eb1c74f816b46166097fef8b26c6"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
url = "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.8.1/kustomize_v5.8.1_windows_arm64.zip"
sha256 = "f6f5090c373965760a30a59af84c81853b80d2c7dbb3236424f440e47eed3f5a"
