name = "opencode"
version = "1.14.37"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/anomalyco/opencode/releases/download/v1.14.37/opencode-linux-x64.tar.gz"
sha256 = "24f887c801d113b31930533aac1433816348006ba61dd8ca0d792bfff4b75960"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/anomalyco/opencode/releases/download/v1.14.37/opencode-linux-arm64.tar.gz"
sha256 = "e5894bebc76a46d4f0b6ca65ff0da81c6b7d578b92601172c3e4e713546cff66"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/anomalyco/opencode/releases/download/v1.14.37/opencode-darwin-x64.zip"
sha256 = "7465c2351e497703d81745f6a61b8eea38263d24a09e0b6fd13a5dcbfeee7198"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/anomalyco/opencode/releases/download/v1.14.37/opencode-darwin-arm64.zip"
sha256 = "2018a64e94ea8ace8ca58ea21668dec5baa1050a64f1cf43581e0ff04d355e74"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/anomalyco/opencode/releases/download/v1.14.37/opencode-windows-x64.zip"
sha256 = "d7da7b4dbd03327b2f8c17a009cec0096774cd22087ec7a1d6d442143b8612fe"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
url = "https://github.com/anomalyco/opencode/releases/download/v1.14.37/opencode-windows-arm64.zip"
sha256 = "f883abe1efd4edd6c996159c603025253df93338f66752f3d632d18a81d35fd7"
