name = "opencode"
version = "1.14.35"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/anomalyco/opencode/releases/download/v1.14.35/opencode-linux-x64.tar.gz"
sha256 = "2e35643de90e5315177e31969ab1cf2af55a8ba9391e5c348f48381bf30c1010"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/anomalyco/opencode/releases/download/v1.14.35/opencode-linux-arm64.tar.gz"
sha256 = "506b5302f93299d4773ca739e8b68138f169cc81deb2bf6930f9f34bce453bb4"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/anomalyco/opencode/releases/download/v1.14.35/opencode-darwin-x64.zip"
sha256 = "80c7b428a01af5860136d72db00e158ff4e5719997883336a141a3ba8c315ccf"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/anomalyco/opencode/releases/download/v1.14.35/opencode-darwin-arm64.zip"
sha256 = "5f7c35c544452ca30a126293d21f341845f19517c6417711fdb4f6aeab40ca5b"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/anomalyco/opencode/releases/download/v1.14.35/opencode-windows-x64.zip"
sha256 = "9ec0498173270a32e22849999a1cf16a92a71a3c25d81f23079b1687b636ef74"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
url = "https://github.com/anomalyco/opencode/releases/download/v1.14.35/opencode-windows-arm64.zip"
sha256 = "7ffac488bd3fa4906d18b137b7382f7ad159463c081acf3da0241fb921ed5759"
