name = "gh"
version = "2.90.0"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/cli/cli/releases/download/v2.90.0/gh_2.90.0_linux_amd64.tar.gz"
sha256 = "b2aef7b23ec6899bf27f37a32c57a7935d0a178568ac33dc9bb03842f724195a"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/cli/cli/releases/download/v2.90.0/gh_2.90.0_linux_arm64.tar.gz"
sha256 = "1139e1ad912fcddb5ef4b957530184c2c30d9937ff65ff4e641fbf6ca5f28c7c"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/cli/cli/releases/download/v2.90.0/gh_2.90.0_macOS_amd64.zip"
sha256 = "e44d23dd5f0f8534d7a9989177f2c60ac8ffbcdfc6a0a6e5d1f23c4a3b83a9e0"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/cli/cli/releases/download/v2.90.0/gh_2.90.0_macOS_arm64.zip"
sha256 = "82a6acdc3f445dc316b70e1bc15b9b7c4b4e26fd30b04de461a7829ad6c6e97f"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/cli/cli/releases/download/v2.90.0/gh_2.90.0_windows_amd64.zip"
sha256 = "73fcae688eb64ae67828536c9be90db1e5be3f11691a6fa1c1e5418fd24ee10b"
