name = "dua-cli"
version = "2.34.0"

[[artifacts]]
target = "x86_64-unknown-linux-musl"
url = "https://github.com/Byron/dua-cli/releases/download/v2.34.0/dua-v2.34.0-x86_64-unknown-linux-musl.tar.gz"
sha256 = "4f2de3f97206d6bca0d15fbb9241f52b1014df35fd7ae362bacf67371164c1a1"

[[artifacts]]
target = "aarch64-unknown-linux-musl"
url = "https://github.com/Byron/dua-cli/releases/download/v2.34.0/dua-v2.34.0-aarch64-unknown-linux-musl.tar.gz"
sha256 = "d77a07e3aa1af12cfd9a60ace5a15395af96040089ba358df76d1621d12b1893"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/Byron/dua-cli/releases/download/v2.34.0/dua-v2.34.0-x86_64-apple-darwin.tar.gz"
sha256 = "c1b346360d0eabee17d43c03e4820fb097e9c334f07dd77708a44355f7b887e7"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/Byron/dua-cli/releases/download/v2.34.0/dua-v2.34.0-x86_64-pc-windows-msvc.zip"
sha256 = "abbd93e4d8eaf4d1b9181310a0240e37fc3d3e107a70870289125c0171fefca9"
