name = "age"
version = "1.3.1"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/FiloSottile/age/releases/download/v1.3.1/age-v1.3.1-linux-amd64.tar.gz"
sha256 = "bdc69c09cbdd6cf8b1f333d372a1f58247b3a33146406333e30c0f26e8f51377"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/FiloSottile/age/releases/download/v1.3.1/age-v1.3.1-linux-arm64.tar.gz"
sha256 = "c6878a324421b69e3e20b00ba17c04bc5c6dab0030cfe55bf8f68fa8d9e9093a"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/FiloSottile/age/releases/download/v1.3.1/age-v1.3.1-darwin-amd64.tar.gz"
sha256 = "2b233301ad21ab7b1eabd9ae1198a164005fa4928fcdd745d47c39f8593209d7"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/FiloSottile/age/releases/download/v1.3.1/age-v1.3.1-darwin-arm64.tar.gz"
sha256 = "01120ea2cbf0463d4c6bd767f99f3271bbed1cdc8a9aa718a76ba1fe4f01998b"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/FiloSottile/age/releases/download/v1.3.1/age-v1.3.1-windows-amd64.zip"
sha256 = "c56e8ce22f7e80cb85ad946cc82d198767b056366201d3e1a2b93d865be38154"
