name = "crosspack"
version = "0.12.0"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.12.0/crosspack-v0.12.0-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "836573dc4226675163be987485dd424951d4a0f072ef6ad6cfff057e44e13b05"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.12.0/crosspack-v0.12.0-aarch64-unknown-linux-gnu.tar.gz"
sha256 = "085b8ee4cf552fa58cd49f3010996205fc937f2fca217463497ecf720ac29190"

[[artifacts]]
target = "x86_64-unknown-linux-musl"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.12.0/crosspack-v0.12.0-x86_64-unknown-linux-musl.tar.gz"
sha256 = "9da2f0112ae5650a0dca64cb4bff185c2b394fba3ee6732517e52d6db68c56c4"

[[artifacts]]
target = "aarch64-unknown-linux-musl"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.12.0/crosspack-v0.12.0-aarch64-unknown-linux-musl.tar.gz"
sha256 = "db4c2066f193ddb60eb073c5536b7c8ff4c5f10672f279f2a5b58ee5fb6fac42"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.12.0/crosspack-v0.12.0-x86_64-apple-darwin.tar.gz"
sha256 = "7c34fe377dc8b8d92a1cfccebdb541da6b5f25b7de2f5bf6a5aa668c35e059db"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.12.0/crosspack-v0.12.0-aarch64-apple-darwin.tar.gz"
sha256 = "fca506ad979369571484ddf5a056e44658a7d54c2c6abc12450b501eb9c1d7f6"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.12.0/crosspack-v0.12.0-x86_64-pc-windows-msvc.zip"
sha256 = "2dad8eb619778c4819e453e2809f231c74d65c16c2a1e7503b8714900484dbed"
