name = "crosspack"
version = "0.13.0"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.13.0/crosspack-v0.13.0-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "c4ec979fc52ee85db480f9fee2cf7b35980f9f8732d0beb6df9be64679da8e7a"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.13.0/crosspack-v0.13.0-aarch64-unknown-linux-gnu.tar.gz"
sha256 = "bd4b2c664ba5191c14496b29421505f017aaf05fd91074d0e6c269c6743dae43"

[[artifacts]]
target = "x86_64-unknown-linux-musl"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.13.0/crosspack-v0.13.0-x86_64-unknown-linux-musl.tar.gz"
sha256 = "230b544df7983bc02bd4eda95e781fb3cf1d10d993e2083d18ebf82df9ce6529"

[[artifacts]]
target = "aarch64-unknown-linux-musl"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.13.0/crosspack-v0.13.0-aarch64-unknown-linux-musl.tar.gz"
sha256 = "cd50c1a931297ce2e6120fc005c0c466386112f29f5ac29d87d3782fb85b83a5"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.13.0/crosspack-v0.13.0-x86_64-apple-darwin.tar.gz"
sha256 = "fb834ad9a9e669bf54c6f7219a48966c5c7be35e78e40d40aefe623e1cc3a3e2"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.13.0/crosspack-v0.13.0-aarch64-apple-darwin.tar.gz"
sha256 = "770821d5181f84c7fa2f604358683e91b445a3f538ec3084c4487fb464f95e82"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.13.0/crosspack-v0.13.0-x86_64-pc-windows-msvc.zip"
sha256 = "9a5efac281afedc02b8af1c26722d7b78d65eb1b41fabb8e83902225b054def8"
