name = "crosspack"
version = "0.14.1"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.14.1/crosspack-v0.14.1-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "f19ee8a7d5704f230ed22325458e87cf1e4bb388065d3924c0737b0b1bf0fd1d"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.14.1/crosspack-v0.14.1-aarch64-unknown-linux-gnu.tar.gz"
sha256 = "aa17a7510b5ea0a1a31bc49081326e00619cdd0c4cd7c904305748cecf7efbbe"

[[artifacts]]
target = "x86_64-unknown-linux-musl"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.14.1/crosspack-v0.14.1-x86_64-unknown-linux-musl.tar.gz"
sha256 = "f74e1d839b207e823a2e9a7d44d15b53c2b7bf48075770b9a72251ad7f21e53e"

[[artifacts]]
target = "aarch64-unknown-linux-musl"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.14.1/crosspack-v0.14.1-aarch64-unknown-linux-musl.tar.gz"
sha256 = "50d130874fb61900a2337111ca58412581c3e3614f9c044ec2a96250b84dd323"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.14.1/crosspack-v0.14.1-x86_64-apple-darwin.tar.gz"
sha256 = "50fd9137742f3ebcb7cfbb2e1efc8250b74ee433894ff2c77dddb3efd3e27c2b"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.14.1/crosspack-v0.14.1-aarch64-apple-darwin.tar.gz"
sha256 = "50d1e0dfc2930896c4effc2d92535795a7fb3d805b0d0cec30ff928db5de4316"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.14.1/crosspack-v0.14.1-x86_64-pc-windows-msvc.zip"
sha256 = "ac0a6ca4649437ce6c63c7a940d768f9db0f945dcf15cdeedd233c7534fd6e18"
