name = "uv"
version = "0.10.10"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/astral-sh/uv/releases/download/0.10.10/uv-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "3e1027f26ce8c7e4c32e2277a7fed2cb410f2f1f9320d3df97653d40e21f415b"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/astral-sh/uv/releases/download/0.10.10/uv-aarch64-unknown-linux-gnu.tar.gz"
sha256 = "2b80457b950deda12e8d5dc3b9b7494ac143eae47f1fb11b1c6e5a8495a6421e"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/astral-sh/uv/releases/download/0.10.10/uv-x86_64-apple-darwin.tar.gz"
sha256 = "dd18420591d625f9b4ca2b57a7a6fe3cce43910f02e02d90e47a4101428de14a"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/astral-sh/uv/releases/download/0.10.10/uv-aarch64-apple-darwin.tar.gz"
sha256 = "8a09f0ef51ee7f7170731b4cb8bde5bf9ba6da5304f49a7df6cdab42a1f37b5d"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/astral-sh/uv/releases/download/0.10.10/uv-x86_64-pc-windows-msvc.zip"
sha256 = "d31a30f1dfb96e630a08d5a9b3f3f551254b7ed6e9b7e495f46a4232661c7252"
