name = "uv"
version = "0.11.0"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/astral-sh/uv/releases/download/0.11.0/uv-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "cc0fbb42b3642125f600a55b0b095bea65cddaadb94c6ea2b6ba5d79c5825089"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/astral-sh/uv/releases/download/0.11.0/uv-aarch64-unknown-linux-gnu.tar.gz"
sha256 = "8e179ca110343a17f801444ff9ef117dba56ef5fc9f6a4c9bb77b318ddba5f24"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/astral-sh/uv/releases/download/0.11.0/uv-x86_64-apple-darwin.tar.gz"
sha256 = "31aaec764166af8885cf99321fd6ed24fef80225a6f26ed1ae8ce04111688a7e"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/astral-sh/uv/releases/download/0.11.0/uv-aarch64-apple-darwin.tar.gz"
sha256 = "0c0f32c6a3473c5928aff96c3233715edfc79290e892f255cac93710cde7b91a"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/astral-sh/uv/releases/download/0.11.0/uv-x86_64-pc-windows-msvc.zip"
sha256 = "e21d00b172df83531564a95e75a2bdc0c59b471dbb3515f0c1b4d6ef657dc451"
