name = "uv"
version = "0.11.3"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/astral-sh/uv/releases/download/0.11.3/uv-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "c0f3236f146e55472663cfbcc9be3042a9f1092275bbe3fe2a56a6cbfd3da5ce"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/astral-sh/uv/releases/download/0.11.3/uv-aarch64-unknown-linux-gnu.tar.gz"
sha256 = "711382e3158433f06b11d99afb440f4416359fc3c84558886d8ed8826a921bff"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/astral-sh/uv/releases/download/0.11.3/uv-x86_64-apple-darwin.tar.gz"
sha256 = "b0e05e0b43a000fdc2132ee3f3400ba5dee427bc2337d3ec4eb8cf4f3d5722af"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/astral-sh/uv/releases/download/0.11.3/uv-aarch64-apple-darwin.tar.gz"
sha256 = "2bc3d0c7bf2bd08325b1e170abac6f7e5b3346e1d4eab3370d17cefec934996f"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/astral-sh/uv/releases/download/0.11.3/uv-x86_64-pc-windows-msvc.zip"
sha256 = "ae681c0aaec7cc96af184648cb88d73f8393ed60fa5880abdd6bdb910f9b227c"
