name = "direnv"
version = "2.37.1"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/direnv/direnv/releases/download/v2.37.1/direnv.linux-amd64"
sha256 = "1f1b93dd6f38523fde26dfac96151ef9d31a374e3005cd3345fb93555ae0c9b5"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/direnv/direnv/releases/download/v2.37.1/direnv.linux-arm64"
sha256 = "2a9cef8d73521d6a3ec3f2871c4b747b8c4cc038628c1b57a7efa42b393a2d82"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/direnv/direnv/releases/download/v2.37.1/direnv.darwin-amd64"
sha256 = "24fb9ce48b563d7e9fbdd3a4e3e836941654a31ce3e67eba9eaafc3dcd8ae73b"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/direnv/direnv/releases/download/v2.37.1/direnv.darwin-arm64"
sha256 = "4f569f3a36732bfd8b8fea7bfcc6ad87a59745c109022164d0ca4832451d5369"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/direnv/direnv/releases/download/v2.37.1/direnv.windows-amd64"
sha256 = "d96fc8b7cf020c2d4c1dbbc2ccec5fd1cab05b51c491f02c8527a7fa6c50a1cd"
