name = "balenaetcher"
license = "Apache-2.0"
homepage = "https://github.com/balena-io/etcher"

[source.release]
kind = "github_releases"
repo = "balena-io/etcher"
tag_prefix = "v"
include_prereleases = false

[source.version]
kind = "github_tag"

[source.checksum]
kind = "download_sha256"

[source.asset]
kind = "release_asset_url"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
asset = "balenaEtcher-linux-x64-{version}.zip"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "balenaetcher"
path = "balenaEtcher.AppImage"

[[artifacts.gui_apps]]
app_id = "io.balena.etcher"
display_name = "balenaEtcher"
exec = "balenaEtcher.AppImage"
categories = ["Utility"]

[[artifacts]]
target = "x86_64-apple-darwin"
asset = "balenaEtcher-{version}-x64.dmg"
strip_components = 0

[[artifacts.binaries]]
name = "balenaetcher"
path = "balenaEtcher.app/Contents/MacOS/balenaEtcher"

[[artifacts.gui_apps]]
app_id = "io.balena.etcher"
display_name = "balenaEtcher"
exec = "balenaEtcher.app"
categories = ["Utility"]

[[artifacts]]
target = "aarch64-apple-darwin"
asset = "balenaEtcher-{version}-arm64.dmg"
strip_components = 0

[[artifacts.binaries]]
name = "balenaetcher"
path = "balenaEtcher.app/Contents/MacOS/balenaEtcher"

[[artifacts.gui_apps]]
app_id = "io.balena.etcher"
display_name = "balenaEtcher"
exec = "balenaEtcher.app"
categories = ["Utility"]

[[artifacts]]
target = "x86_64-pc-windows-msvc"
asset = "balenaEtcher-win32-x64-{version}.zip"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "balenaetcher"
path = "balenaEtcher.exe"

[[artifacts.gui_apps]]
app_id = "io.balena.etcher"
display_name = "balenaEtcher"
exec = "balenaEtcher.exe"
categories = ["Utility"]
