name = "direnv"
license = "MIT"
homepage = "https://github.com/direnv/direnv"

[[shell_init]]
name = "direnv"
binary = "direnv"
strategy = "eval_stdout"
bash = ["hook", "bash"]
zsh = ["hook", "zsh"]
fish = ["hook", "fish"]
powershell = ["hook", "pwsh"]

[source]
provider = "github"
repo = "direnv/direnv"
tag_prefix = "v"
include_prereleases = false

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
asset = "direnv.linux-amd64"
archive = "bin"
strip_components = 0

[[artifacts.binaries]]
name = "direnv"
path = "direnv"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
asset = "direnv.linux-arm64"
archive = "bin"
strip_components = 0

[[artifacts.binaries]]
name = "direnv"
path = "direnv"

[[artifacts]]
target = "x86_64-apple-darwin"
asset = "direnv.darwin-amd64"
archive = "bin"
strip_components = 0

[[artifacts.binaries]]
name = "direnv"
path = "direnv"

[[artifacts]]
target = "aarch64-apple-darwin"
asset = "direnv.darwin-arm64"
archive = "bin"
strip_components = 0

[[artifacts.binaries]]
name = "direnv"
path = "direnv"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
asset = "direnv.windows-amd64"
archive = "bin"
strip_components = 0

[[artifacts.binaries]]
name = "direnv"
path = "direnv.exe"
