name = "eza"
license = "MIT"
homepage = "https://github.com/eza-community/eza"

[source]
provider = "github"
repo = "eza-community/eza"
tag_prefix = "v"
include_prereleases = false

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
asset = "eza_x86_64-unknown-linux-gnu.tar.gz"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "eza"
path = "eza"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
asset = "eza_aarch64-unknown-linux-gnu.tar.gz"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "eza"
path = "eza"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
asset = "eza.exe_x86_64-pc-windows-gnu.zip"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "eza"
path = "eza.exe"
