name = "python"
license = "Python-2.0"
homepage = "https://github.com/astral-sh/python-build-standalone"

[source.release]
kind = "github_releases"
repo = "astral-sh/python-build-standalone"
include_prereleases = false

[source.version]
kind = "asset_name_regex"
pattern = '^cpython-(3\.14\.\d+\+{tag_name})-'

[source.checksum]
kind = "asset_digest"

[source.asset]
kind = "release_asset_url"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
asset = "cpython-{version}-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "python"
path = "bin/python3"
[[artifacts.binaries]]
name = "python3"
path = "bin/python3"
[[artifacts.binaries]]
name = "python3.14"
path = "bin/python3.14"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
asset = "cpython-{version}-aarch64-unknown-linux-gnu-install_only_stripped.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "python"
path = "bin/python3"
[[artifacts.binaries]]
name = "python3"
path = "bin/python3"
[[artifacts.binaries]]
name = "python3.14"
path = "bin/python3.14"

[[artifacts]]
target = "x86_64-apple-darwin"
asset = "cpython-{version}-x86_64-apple-darwin-install_only_stripped.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "python"
path = "bin/python3"
[[artifacts.binaries]]
name = "python3"
path = "bin/python3"
[[artifacts.binaries]]
name = "python3.14"
path = "bin/python3.14"

[[artifacts]]
target = "aarch64-apple-darwin"
asset = "cpython-{version}-aarch64-apple-darwin-install_only_stripped.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "python"
path = "bin/python3"
[[artifacts.binaries]]
name = "python3"
path = "bin/python3"
[[artifacts.binaries]]
name = "python3.14"
path = "bin/python3.14"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
asset = "cpython-{version}-x86_64-pc-windows-msvc-install_only_stripped.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "python"
path = "python.exe"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
asset = "cpython-{version}-aarch64-pc-windows-msvc-install_only_stripped.tar.gz"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "python"
path = "python.exe"

[[integrations]]
kind = "man_page"
platforms = ["linux", "macos"]
section = "1"
source = "share/man/man1/*.1"
