name = "watchexec"
license = "Apache-2.0"
homepage = "https://github.com/watchexec/watchexec"

[source.release]
kind = "github_releases"
repo = "watchexec/watchexec"
tag_prefix = "v"
include_prereleases = false

[source.checksum]
kind = "download_sha256"

[source.asset]
kind = "release_asset_url"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
asset = "watchexec-{version}-x86_64-unknown-linux-gnu.tar.xz"
archive = "tar.xz"
strip_components = 1

[[artifacts.binaries]]
name = "watchexec"
path = "watchexec"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
asset = "watchexec-{version}-aarch64-unknown-linux-gnu.tar.xz"
archive = "tar.xz"
strip_components = 1

[[artifacts.binaries]]
name = "watchexec"
path = "watchexec"

[[artifacts]]
target = "x86_64-apple-darwin"
asset = "watchexec-{version}-x86_64-apple-darwin.tar.xz"
archive = "tar.xz"
strip_components = 1

[[artifacts.binaries]]
name = "watchexec"
path = "watchexec"

[[artifacts]]
target = "aarch64-apple-darwin"
asset = "watchexec-{version}-aarch64-apple-darwin.tar.xz"
archive = "tar.xz"
strip_components = 1

[[artifacts.binaries]]
name = "watchexec"
path = "watchexec"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
asset = "watchexec-{version}-x86_64-pc-windows-msvc.zip"
archive = "zip"
strip_components = 1

[[artifacts.binaries]]
name = "watchexec"
path = "watchexec.exe"
