name = "xh"
license = "MIT"
homepage = "https://github.com/ducaale/xh"

[source.release]
kind = "github_releases"
repo = "ducaale/xh"
tag_prefix = "v"
include_prereleases = false

[source.checksum]
kind = "download_sha256"

[source.asset]
kind = "release_asset_url"

[[artifacts]]
target = "x86_64-unknown-linux-musl"
asset = "xh-v{version}-x86_64-unknown-linux-musl.tar.gz"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "xh"
path = "xh"

[[artifacts]]
target = "aarch64-unknown-linux-musl"
asset = "xh-v{version}-aarch64-unknown-linux-musl.tar.gz"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "xh"
path = "xh"

[[artifacts]]
target = "x86_64-apple-darwin"
asset = "xh-v{version}-x86_64-apple-darwin.tar.gz"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "xh"
path = "xh"

[[artifacts]]
target = "aarch64-apple-darwin"
asset = "xh-v{version}-aarch64-apple-darwin.tar.gz"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "xh"
path = "xh"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
asset = "xh-v{version}-x86_64-pc-windows-msvc.zip"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "xh"
path = "xh.exe"
