name = "zoxide"
license = "MIT"
homepage = "https://github.com/ajeetdsouza/zoxide"

[source]
provider = "github"
repo = "ajeetdsouza/zoxide"
tag_prefix = "v"
include_prereleases = false

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
asset = "zoxide-{version}-x86_64-unknown-linux-musl.tar.gz"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "zoxide"
path = "zoxide"

[[artifacts.completions]]
shell = "bash"
path = "completions/zoxide.bash"

[[artifacts.completions]]
shell = "zsh"
path = "completions/_zoxide"

[[artifacts.completions]]
shell = "fish"
path = "completions/zoxide.fish"

[[artifacts.completions]]
shell = "powershell"
path = "completions/_zoxide.ps1"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
asset = "zoxide-{version}-aarch64-unknown-linux-musl.tar.gz"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "zoxide"
path = "zoxide"

[[artifacts.completions]]
shell = "bash"
path = "completions/zoxide.bash"

[[artifacts.completions]]
shell = "zsh"
path = "completions/_zoxide"

[[artifacts.completions]]
shell = "fish"
path = "completions/zoxide.fish"

[[artifacts.completions]]
shell = "powershell"
path = "completions/_zoxide.ps1"

[[artifacts]]
target = "x86_64-apple-darwin"
asset = "zoxide-{version}-x86_64-apple-darwin.tar.gz"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "zoxide"
path = "zoxide"

[[artifacts.completions]]
shell = "bash"
path = "completions/zoxide.bash"

[[artifacts.completions]]
shell = "zsh"
path = "completions/_zoxide"

[[artifacts.completions]]
shell = "fish"
path = "completions/zoxide.fish"

[[artifacts.completions]]
shell = "powershell"
path = "completions/_zoxide.ps1"

[[artifacts]]
target = "aarch64-apple-darwin"
asset = "zoxide-{version}-aarch64-apple-darwin.tar.gz"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "zoxide"
path = "zoxide"

[[artifacts.completions]]
shell = "bash"
path = "completions/zoxide.bash"

[[artifacts.completions]]
shell = "zsh"
path = "completions/_zoxide"

[[artifacts.completions]]
shell = "fish"
path = "completions/zoxide.fish"

[[artifacts.completions]]
shell = "powershell"
path = "completions/_zoxide.ps1"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
asset = "zoxide-{version}-x86_64-pc-windows-msvc.zip"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "zoxide"
path = "zoxide.exe"

[[artifacts.completions]]
shell = "bash"
path = "completions/zoxide.bash"

[[artifacts.completions]]
shell = "zsh"
path = "completions/_zoxide"

[[artifacts.completions]]
shell = "fish"
path = "completions/zoxide.fish"

[[artifacts.completions]]
shell = "powershell"
path = "completions/_zoxide.ps1"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
asset = "zoxide-{version}-aarch64-pc-windows-msvc.zip"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "zoxide"
path = "zoxide.exe"

[[artifacts.completions]]
shell = "bash"
path = "completions/zoxide.bash"

[[artifacts.completions]]
shell = "zsh"
path = "completions/_zoxide"

[[artifacts.completions]]
shell = "fish"
path = "completions/zoxide.fish"

[[artifacts.completions]]
shell = "powershell"
path = "completions/_zoxide.ps1"
